# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongo-port
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: mongdob
        image: foxish/mongodb
        args:
          - --replSet "rs0"
        ports:
        - containerPort: 27017
          protocol: TCP
          name: mongo-port
        volumeMounts:
          - name: data
            mountPath: /var/lib/mongodb
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi