apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
    - name: mongodb
      image: sameersbn/mongodb
      ports:
        - containerPort: 27017
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/mongodb
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mongo-data