apiVersion: v1
kind: Service
metadata:
  name: mongodb-ext
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    name: mongodb
